Update patch set 1
Patch Set 1:

Resolving Dependencies
--> Running transaction check
---> Package sf-release.noarch 0:9999.10.gedf0a29-10.el7 will be installed                                                         
--> Processing Dependency: centos-release-openstack-queens for package: sf-release-9999.10.gedf0a29-10.el7.noarch                  
--> Processing Dependency: centos-release-scl-rh for package: sf-release-9999.10.gedf0a29-10.el7.noarch                            
--> Finished Dependency Resolution
Error: Package: sf-release-9999.10.gedf0a29-10.el7.noarch (/sf-release-9999.10.gedf0a29-10.el7.noarch)                             
           Requires: centos-release-scl-rh
Error: Package: sf-release-9999.10.gedf0a29-10.el7.noarch (/sf-release-9999.10.gedf0a29-10.el7.noarch)                             
           Requires: centos-release-openstack-queens
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[cloud-user@managesf ~]$ sudo -

Patch-set: 1